name: Compile JOSS Paper

on:
  push:
    branches:
      - main
    paths:
      - 'JOSSpaper/**'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Compile Paper
      uses: openjournals/inara-action@v1
      with:
        journal: joss
        path: 'JOSSpaper'

    - name: Upload Compiled Paper as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-paper
        path: JOSSpaper/paper.pdf
